### ISSUE TITLE
dnscrypt-proxy was removed, evaluation fails

### ISSUE THREAD

**Issue by Profpatsch** [openlab-aux/vuizvui#17]
https://github.com/NixOS/nixpkgs/issues/33540

Only @devhell uses it at the moment, but all channel evaluations fail nonetheless.

**Comment by devhell** [comment]
Dammit. Thanks for the headsup @Profpatsch :beer:

**Comment by vcunat** [comment]
It should get back to nixpkgs soon.

**Comment by Profpatsch** [comment]
Back again: https://github.com/NixOS/nixpkgs/pull/33629

**Comment by devhell** [comment]
Cheers @Profpatsch and @vcunat
