### ISSUE TITLE
Guix' Antichamber crashes after first display with `undefined symbol: MinorityMix_SetPosition`

### ISSUE THREAD

**Issue by Ambrevar** [openlab-aux/vuizvui#30]
Hello dear Nix users!

Sorry for intruding with Guix here but I figured that you people were the closest the the problem I'm trying to solve! :)  So maybe you'll have a hunch.

I'm trying to package Antichamber for Guix:
https://gitlab.com/guix-gaming-channels/games/merge_requests/19

You can skip the long monologue, only the last post is important:
the game starts and displays the first room, but it almost immediately crashes.
Here is the log:
```
> ./bin/antichamber 
[S_API FAIL] SteamAPI_Init() failed; SteamAPI_IsSteamRunning() failed.
[S_API FAIL] SteamAPI_Init() failed; unable to locate a running instance of Steam, or a local steamclient.dll.
Loading library: libPhysXCooking.so
Result of loading library libPhysXCooking.so: 0x9af6580
Loading library: PhysXUpdateLoader.so
ERROR: PhysXUpdateLoader.so: cannot open shared object file: No such file or directory
Result of loading library PhysXUpdateLoader.so: 0x0
Loading library: libPhysXCore.so
Result of loading library libPhysXCore.so: 0x9de3c80
antichamber: symbol lookup error: antichamber: undefined symbol: MinorityMix_SetPosition
```

Any idea where this could come from?

The Nix Antichamber discussion is here: https://github.com/openlab-aux/vuizvui/pull/14.
Thanks in advance ;)

**Comment by aszlig** [comment]
@Ambrevar: Well, no problem with Guix, after all we're using the same store :-) However, I don't have time to look into this right now (plus I haven't even played the game *at all*), so maybe @Profpatsch or @layus can say more about this.

**Comment by layus** [comment]
I cannot help much, I never encountered this issue. But you already made a great job at working around other issues :-).

I found https://github.com/solus-project/linux-steam-integration/issues/58 that looks a lot like your issue. But I have no idea what LSI is ;-)

Arch also has a reference to the missing symbol. https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=antichamber. If I understand correctly, it means that the version of libSDL2_mixer that we build has missing symbols, and that you should use the version bundled with the game, possibly with the right patchelf so the lib is found.

**Comment by Ambrevar** [comment]
@layus Thank you so much, this was it!  I'm now using the embedded SDL2-mixer and it works!
I've tried different version of SDL2-mixer (including 2.0.0) and it didn't cut, so I believe the Antichambers developer patched it and shipped their own version (effectively making it a closed source, proprietary dependency :().

**Comment by layus** [comment]
Glad it worked :-).
