### ISSUE TITLE
Proposal: Allow ALL the URIs!

### ISSUE THREAD

**Issue by sternenseemann** [openlab-aux/vuizvui#50]
### Motivation

As you can probably guess, the main motivation for this is #40: It would be nice if we could fetch tvl's depot at eval time with `builtins.fetchGit` and additionally depot _needs_ `builtins.fetchTarball` and `builtins.fetchGit` as well for the following purposes:

* At eval time for fetching its pinned version of `<nixpkgs>`
* At build time for fetching some sources, like for example [`third_party.lisp.cl-base64`](https://cs.tvl.fyi/depot/-/blob/third_party/lisp/cl-base64.nix#L4-7)

Both of these things will break evaluation on hydra at the moment due to its `allowed-uris` settings for `restricted-eval`. The proposal is to change the evaluation settings for hydra, how exactly is described later.

### Alternative solutions

I have already explored some alternative solutions to changing the settings for `restricted-eval`.

#### Using import from derivation

One ace we have up our sleeve is that our Hydra allows import-from-derivation. We can simply use `pkgs.fetchgit` to get the `tvl` sources and import them, as done in 823cfe3e63568fe89871751715cddf53a435033e. However, depot still uses `builtins.fetchTarball` to fetch `<nixpkgs>` as described above, breaking evaluation.

This can be aleviated only by patching upstream which I have experimented with in [CL/2552](https://cl.tvl.fyi/c/depot/+/2552) which I used in 9fb6abfee5c31e44b86d4a250e479ad26b4acdab to let depot inherit `pkgs` from vuizvui, tying it to our `nixpkgsSrc` advances. This fixes evaluation of depot, but doesn't solve our issues completely, as there are still derivations in depot which wouldn't build due to their usage of builtin fetchers for `src`. We could of course try to patch upstream, but this would also lead to an ongoing maintenance effort as fetcher discipline wouldn't be enforced upstream.

Additionally it introduces a new issue, namely the potential for substantial breakage: depot has its own `<nixpkgs>` pin and with good reason:Pin updates reveal [substantial](https://cl.tvl.fyi/c/depot/+/2538) [breakage](https://cl.tvl.fyi/c/depot/+/2341) [introduced](https://cl.tvl.fyi/c/depot/+/2341) [in unstable](https://cl.tvl.fyi/c/depot/+/2295). Letting depot inherit our `nixpkgsSrc` advances may lead to breakage we can't immediately fix ourselves.

Initial results from this test run where promising though: I [added a single unproblematic package from depot to my system configuration](https://github.com/openlab-aux/vuizvui/commit/cd32f5ddb5e2d80a5b65fc5505bec0694e0e0313) and this evaluated [successfully on Hydra](https://headcounter.org/hydra/eval/481584) (even [twice](https://headcounter.org/hydra/eval/481575)). What's more, the eval time was seemingly not negatively impacted by this, clocking in at a perfectly normal 20 minutes.

#### Using flakes

This would have the requirement first, that we'd need to convert vuizvui to flakes and use `flakes-compat` for the remaining stable users which seem to be me, @Profpatsch and @‍devhell at the moment.

Additionally, we'd still run into the same problems as described above with the import-from-derivation approach. Since the same evaluation restrictions apply (if not more?!).

#### Adding an additional input for depot

Not desireable, because:

* Additional Hydra administrative work
* We want to pin depot to minimize breakage

### Why not builtin fetchers?

Our current settings in `vuizvui` make using builtin fetchers basically impossible. Instead, all necessary downloads for evaluation (`nixpkgsSrc` and `vuizvuiSrc`) are done by Hydra. This is especially nice because Hydra can continuously update both sources from `git`, meaning we don't have to trigger builds manually or update pinned versions of inputs.

The question is, however, why would we essentially forbid builtin fetcher? Generally there are two main reasons, I can think of:

* Builtin fetchers can introduce impurities to evaluation: `builtins.fetchGit`, for example, can be pointed to a repository and told to just fetch the latest revision. This impurity is often not a good which is why you can disable this feature using the nix option `pure-eval`.
* Builtin fetchers allow the evaluation to depend on the network: `builtins.fetchGit` downloads the needed sources *during evaluation*. Often you'd want to enforce that hydra fetches everything necessary for evaluation and only builds would then depend on the network. However, we already allow this because we don't forbid import-from-derivation: `import (builtins.fetchGit { … })` is not different from the allowed `import (pkgs.fetchgit { … })`.

As it stands, there seems to be no reason why we wouldn't allow builtin fetchers with `pure-eval` enabled. The only problem we need to solve is a configuration which doesn't require us to update `allowed-uris` all the time, as we probably don't want to disable `restrict-eval`.

### Proposal

Therefore I'd propose to change the nix config used for evaluating stuff on hydra to something along the lines of the following:

```
restrict-eval = true
pure-eval = true
allow-import-from-derivation = true
allowed-uris = https:// http:// ftp:// gopher:// # and possibly more protocols
```

This has the following effect:

* We only allow builtin fetchers with pinned git revision or sha256 (`pure-eval`)
* We allow builtin fetchers to fetch _any url_ with one of the given protocols. This works because `allowed-uris` just matches a prefix.
* We disallow access to any non-network paths except the inputs via `restricted-eval` (as it has been)

To me, this is a no-brainer: We don't introduce any impurities into evaluation (thanks to `pure-eval`), we don't allow anything which wasn't already possible with import-from-derivation (except now with less overhead) and most we most likely won't ever need to touch the configuration again, as there is no URI list to be updated.

PS: An ancient meme for your viewing pleasure.

![allow all the uris](https://sterni.lv/tmp/allow-all-the-uris.png)

**Comment by aszlig** [comment]
Addressed via the ugliest patch possible for now, but mid/long term we should switch to either a better solution or a better patch which can be upstreamed.

Here's the ugly patch for reference:

```diff
diff --git a/src/hydra-eval-jobs/hydra-eval-jobs.cc b/src/hydra-eval-jobs/hydra-eval-jobs.cc
index 44a273a9..b2fbc09f 100644
--- a/src/hydra-eval-jobs/hydra-eval-jobs.cc
+++ b/src/hydra-eval-jobs/hydra-eval-jobs.cc
@@ -288,6 +288,10 @@ int main(int argc, char * * argv)
            'getEnv', 'currentSystem' etc. */
         evalSettings.pureEval = pureEval;
 
+        if (!pureEval) {
+            evalSettings.allowedUris.set("https:// http:// ftp:// gopher://", false);
+        }
+
         if (myArgs.dryRun) settings.readOnlyMode = true;
 
         if (myArgs.releaseExpr == "") throw UsageError("no expression specified");
```
