### ISSUE TITLE
gog games builder

### ISSUE THREAD

**Issue by TravisDavis-ops** [openlab-aux/vuizvui#52]
after some hunting i came across you repo, do your gog releated things still work. I would like to try then on some games in  my collection

**Comment by Profpatsch** [comment]
The captcha solver seems to be broken:

```
> nix-build -A  pkgs.games.gog.crosscode
…
Solving a captcha is required to log in.
Please run /nix/store/v6kxbdll5q9z7d0iyf8hdc3cmrfgx8jr-get-captcha/bin/get-captcha now.
Waiting for connection..... connected.
Waiting for captcha to be solved...
Captcha solved correctly, logging in.
```

but the window that opens doesn’t have a captcha:

![screenshot](https://user-images.githubusercontent.com/3153638/137618995-f2f9143e-65cd-4b71-81d5-c5ab5030a07f.png)

**Comment by TravisDavis-ops** [comment]
Sorry but I wasnt asking about that part,  I was talking about buildUnity

**Comment by Profpatsch** [comment]
Hm, I guess @aszlig would know about that.

**Comment by aszlig** [comment]
@TravisDavis-ops: The `buildGame` and `buildUnity` functions should be generic enough and while I haven't used them in the last two weeks, they *should* still work. If not, please report an issue. Thanks :-)
